[package]
name = "sppark"
version = "0.1.6"
edition = "2021"
description = "Zero-knowledge template library"
repository = "https://github.com/supranational/sppark"
categories = ["cryptography"]
keywords = ["crypto", "zero-knowledge", "cuda"]
license = "Apache-2.0"
links = "sppark"
include = [
    "/Cargo.toml",
    "/build.rs",
    "/src/**",
    "/sppark/ec/**",
    "/sppark/ff/**",
    "/sppark/msm/**",
    "/sppark/ntt/**",
    "/sppark/util/**",
]

[dependencies]

[build-dependencies]
cc = "^1.0.70"
which = "^4.0"
